### PR TITLE
Add plugin-test to github workflow

### PR DESCRIPTION
**Pull request by Naturalclar**
Part of asdf-community/.github#2

Added github actions workflow for plugin tests

### CODE REVIEW

**Comment by Naturalclar** [comment]
```
  ∗ Downloading and installing opam...
  The installation was successful!
  2.0.5
  FAILED: Incorrect permissions on /tmp/asdf.b4Bc/plugins/opam/bin/install. Must be executable by asdf
  ##[error]Action failed with error Error: The process 'asdf' failed with exit code 1
  ##[error]Node run failed with exit code 1
```

Not too sure how this could be solved, could you check this out? @imbsky

**Comment by imbsky** [comment]
I forgot to fix the code in this repository! Everything is fine now!

**Comment by imbsky** [comment]
Thanks @Naturalclar for your contribution!

**Comment by imbsky** [comment]
@all-contributors please add @Naturalclar for infra

**Pull request merged**
